######################################################################
# Automatically generated by qmake (3.1) Mon Mar 17 01:17:18 2025
######################################################################

QT += core gui widgets multimedia multimediawidgets
CONFIG += c++14
DESTDIR = build
TEMPLATE = app
TARGET = QT_with_Cursor
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += build/ui_test_qt.h \
           src/cameracontrolui.h \
           src/dbgout.h \
           src/mainui.h \
           src/test_qt.h \
           src/ui/cameracontrolui.h \
           src/ui/mainui.h \
           build/test_qt_autogen/include/ui_test_qt.h \
           build/test_qt_autogen/UVLADIE3JM/moc_test_qt.cpp \
           /build/ui_test_qt.h
FORMS += src/test_qt.ui
SOURCES += src/cameracontrolui.cpp \
           src/dbgout.cpp \
           src/main.cpp \
           src/mainui.cpp \
           src/test_qt.cpp \
           build/test_qt_autogen/mocs_compilation.cpp \
           src/ui/cameracontrolui.cpp \
           src/ui/mainui.cpp \
           build/CMakeFiles/3.29.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/CMakeFiles/test_qt.dir/compiler_depend.ts \
                build/CMakeFiles/test_qt_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/test_qt_autogen_timestamp_deps.dir/compiler_depend.ts
